[book]
title = "Rust Embedded MB2 Discovery Book"
description = "Discover the world of microcontrollers through Rust with the BBC micro:bit v2"
authors = ["Rust Embedded Resources Team"]
language = "es"

[output.html]
git-repository-url = "https://github.com/rust-embedded/discovery-mb2/"
additional-js = ["src/assets/epub-link.js"]
additional-css = ["src/assets/custom.css"]

[output.epub]
# Optional settings
title = "Rust Embedded MB2 Discovery Book"
author = "Rust Embedded Resources Team"

# [output.html.site]
# url = "/"
# Optional settings
# base-url = "/discovery-mb2/"
# git-repository-url = "

[output.pdf]
title = "Rust Embedded MB2 Discovery Book"
author = "Rust Embedded Resources Team"
landscape = false
scale = 0.7
paper-width = 8.27
paper-height = 11.7
margin-top = 0.5
margin-bottom = 0.5
margin-left = 0.5
margin-right = 0.5
